package com.mysql.mybatis;

public class TestUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.birthday
     *
     * @mbggenerated
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_user.longcontent
     *
     * @mbggenerated
     */
    private String longcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.id
     *
     * @return the value of test_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.id
     *
     * @param id the value for test_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.name
     *
     * @return the value of test_user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.name
     *
     * @param name the value for test_user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.birthday
     *
     * @return the value of test_user.birthday
     *
     * @mbggenerated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.birthday
     *
     * @param birthday the value for test_user.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_user.longcontent
     *
     * @return the value of test_user.longcontent
     *
     * @mbggenerated
     */
    public String getLongcontent() {
        return longcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_user.longcontent
     *
     * @param longcontent the value for test_user.longcontent
     *
     * @mbggenerated
     */
    public void setLongcontent(String longcontent) {
        this.longcontent = longcontent == null ? null : longcontent.trim();
    }
}