package com.oracle.mybatis;

import java.math.BigDecimal;

public interface TestUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_USER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_USER
     *
     * @mbggenerated
     */
    int insert(TestUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_USER
     *
     * @mbggenerated
     */
    int insertSelective(TestUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_USER
     *
     * @mbggenerated
     */
    TestUser selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TestUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TestUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TestUser record);
}